### ISSUE TITLE
[QUESTION] - Why only for windows?

### ISSUE THREAD

**Issue by ayoungh** [ImNotLiam/WWIIStatsViewer#4]
Seems like you have gone the windows route? Will this be for mac too?

**Comment by ImNotLiam** [comment]
I just haven't had time to build it for mac at the moment. will update it this weekend.

**Comment by ayoungh** [comment]
Thanks Liam, appreciate it, did you used to have a live version? Cause I’m
sure I’ve tried this a week or so ago?

**Comment by ImNotLiam** [comment]
Mac version has been added: https://github.com/ImNotLiam/WWIIStatsViewer/releases/tag/1.1.2.1

**Comment by ayoungh** [comment]
Thank's dude :) 👍
